### ISSUE TITLE
Hi ! Is docker still running ? qaq

### ISSUE THREAD

**Issue by yxt7979** [xinyazhang/PuzzleTunnelDiscovery#1]
![image](https://user-images.githubusercontent.com/62125435/136656800-7f1a2fb3-db51-4d43-96a1-063c69277006.png)

**Comment by xinyazhang** [comment]
Hello,
It seems your docker daemon has not been started. Try the following command and see if it helps
```systemctl enable docker.service```

**Comment by yxt7979** [comment]
thanks! It works after I use ubuntu instead of Ubuntu20.04LTS
